on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.AONFREE_FTP_SERVER }}
        port: 21
        username: ${{ secrets.AONFREE_FTP_USERNAME }}
        password: ${{ secrets.AONFREE_FTP_PASSWORD }}
        server-dir: ${{ secrets.AONFREE_SERVER_DIR }}
        exclude: |
                  **/.git*
                  **/.git*/**
                 
